### ISSUE TITLE
bmvc_subset

### ISSUE THREAD

**Issue by lyupei** [gulvarol/bodynet#1]
Hi,
thanks for your great work and source code!

I'm using the preprocess_up_segm.m to process the dataset, but I don't know where to get the bmvc_subset so the scrpt aborted.

**Comment by gulvarol** [comment]
Sorry for the unclear path. It is under `bodynet/preprocessing/misc/bmvc_subset/`.

**Comment by lyupei** [comment]
got it! 3ks for reply!
