### ISSUE TITLE
PCKh/head size calculation

### ISSUE THREAD

**Issue by fleinen** [gulvarol/bodynet#14]
Hi Gül,

according to your BodyNet paper, you're using PCKh@0.5 metric for evaluating the performance of the 2D pose estimation. Newell et al. refer to PCKh as a "distance [that] is normalized by a fraction of the head size."
Is the calculation of PCKh included in this repo? The only PCK related calculations I found are in eval.lua [L14](https://github.com/gulvarol/bodynet/blob/f07dec69a6490ecdeb1dfd3758e76a3ca5887e5b/training/util/eval.lua#L14) and [L93](https://github.com/gulvarol/bodynet/blob/f07dec69a6490ecdeb1dfd3758e76a3ca5887e5b/training/util/eval.lua#L93). While L14 seems to be a generic implementation, the call in L93 seems to calculate the PCK@0.05 metric assuming that the image/heatmap fits the person.
How did you calculate the head size/PCKh for the evaluation in your paper?
Thanks in advance.

Best,
Fabian

**Comment by gulvarol** [comment]
Hi Fabian,

Thanks for reporting this issue. You are right, the calculation in this repo is not PCKh. These functions were taken from the official repository and I hadn't realized their note before:

https://github.com/princeton-vl/pose-hg-train#training-accuracy-metric
https://github.com/princeton-vl/pose-hg-train/issues/41

So the numbers in the Table A.1 of the supplemental material correspond directly to the output of our released code.

Best,
Gul
