### ISSUE TITLE
camera Intrinsic parameters 

### ISSUE THREAD

**Issue by rafikg** [gulvarol/bodynet#3]
@gulvarol  Thanks for the great work. I read that you have supposed that the camera intrinsic parameters are known during the training. So, what did you do during the inference mode? Do you need camera intrinsic parameters during inference?

**Comment by gulvarol** [comment]
For shape: I had an approximate projection, so I just scale the volume with a constant that I compute from the 2D segmentation map: https://github.com/gulvarol/bodynet/blob/master/fitting/fit_surreal.py#L129
This is undoing the operation that was done to the ground truth volume at training: https://github.com/gulvarol/bodynet/blob/master/training/util/voxelutils.lua#L3
