### ISSUE TITLE
FV and SV image input

### ISSUE THREAD

**Issue by bnathoo** [gulvarol/bodynet#8]
Hi Gul

Is it possible to input front and side view images to generate the final product like you have done in training to provide more accurate volume representations. If so how do we do this?

Thanks

**Comment by gulvarol** [comment]
Hi, I am not sure I understand the question. 'FV/SV image as input and voxel as output' is something I didn't try. You can try by adapting the code. It is similar to 'segmentation in, voxel out' as in [here](https://github.com/gulvarol/bodynet/blob/master/training/models/hg_voxels_b256.lua#L47). My use of FV/SV is more like a constraint on the output.

**Comment by bnathoo** [comment]
Thanks for the quick reply Gul. Just to clarify, when I refer to FV and SV image input I assumed you input 2 images for silhouette reprojection as noted in table 2 of your paper (lines 6, 8 & 10) and also in the training section of the readme file under subnet 5 and bodynet. 

You mentioned your use of FV/SV is more like a constraint on the output which is great, but how do you input the FV/SV images together to act as the constraint when currently the system does not allow for multiple image input? 

Hopefully that clears up my query a bit. Thanks

**Comment by gulvarol** [comment]
No, I do not input the FV/SV images to the network, they act as ground truth. So I add them to the ground truth table, e.g. [here](https://github.com/gulvarol/bodynet/blob/master/training/train.lua#L245). I set the [fields](https://github.com/gulvarol/bodynet/blob/master/training/donkey.lua#L604) of the `instance` in the data loader.

**Comment by bnathoo** [comment]
Thanks Gul
