### ISSUE TITLE
improved accuracy

### ISSUE THREAD

**Issue by bnathoo** [gulvarol/bodynet#9]
Hi Gul 

Did you do any experimentation to improve accuracy of the bodynet output, and did it make any difference? For example I am thinking of something like adjusting the down and up sampling and all input so they are all 128 x128 or something like that. I am looking at figure A4 of your paper when considering this option to improve accuracy. My thought is that higher resolution input images could improve accuracy and reduce the overall error to produce a closer 3D volumetric mesh, especially moving closer to body extremities. I understand this would increase computational time, but just wanted to get your thoughts on this and see if you did any testing on this. 

I hope this makes sense and look forward to your response. Thanks for all your help so far. 

Bhavesh

**Comment by gulvarol** [comment]
Hi Bhavesh, no I didn't play with the architecture. I am sure there are many ways to get improvement from there. The final upsampling layer doesn't have skip connections which might be limiting, too. Also, you can try different ways to fuse modalities other than concatenating. Another thing I never had the time to try is 3D convolutions.

**Comment by bnathoo** [comment]
Thanks for all your help Gul.
